name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - 'ml-service/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'ml-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: jobsight
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ML dependencies and start service
        run: |
          python -m venv ml-service/venv
          source ml-service/venv/bin/activate
          pip install -r ml-service/requirements.txt
          PYTHONPATH=ml-service ml-service/venv/bin/uvicorn ml-service.app.main:app --host 0.0.0.0 --port 5001 &
          until curl --output /dev/null --silent --head --fail http://localhost:5001/docs; do
            echo "Waiting for ML service to start..."
            sleep 2
          done

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run Backend Tests
        working-directory: backend
        run: mvn clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/jobsight
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres