name: ML Service CI

on:
  push:
    paths:
      - 'ml-service/**'
  pull_request:
    paths:
      - 'ml-service/**'

jobs:
  test-ml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ml-service
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start ML service
        run: |
          cd ml-service
          uvicorn main:app --host 0.0.0.0 --port 5001

      - name: Run tests
        working-directory: ml-service
        run: |
          source venv/bin/activate
          pytest